### ISSUE TITLE
StringChecks.UUID_PATTERN doesn't support uppercase

### ISSUE THREAD

**Issue by yohanan** [busybusy/DBC-Android#18]
thanks for the library!

appears `StringCondition.isValidUUID` --- which employs `StringChecks.UUID_PATTERN` ---
 assumes the UUID string is lower-case.   UUID strings, however, can be mixed case.

**Comment by trevjonez** [comment]
I'll see if I can throw together a PR tonight unless someone beats me to it.

**Comment by trevjonez** [comment]
@yohanan `compile 'com.github.busybusy:DBC-Android:1.6.1'`

**Comment by yohanan** [comment]
i'm getting the following when i bump the version version to `1.6.1` --- if i go back to `1.6.0`, i'm fine.  i don't believe i'm using the 'java' gradle plugin.

also, i had to bump my support lib from `25.3.1` to `25.4.0` when i attempted the move to `1.6.1`.

```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
```

**Comment by trevjonez** [comment]
interesting. looks like the 3.0.0 alpha plugin doesn't desugar the way I thought it did. I'll revert that back to the retrolambda config. Not the bleeding edge for no reason.

**Comment by simon-the-canadian** [comment]
@yohanan try compile 'com.github.busybusy:DBC-Android:1.6.2'

**Comment by yohanan** [comment]
works now.  thanks!
