### ISSUE TITLE
Add fails method to `BlockChecks`

### ISSUE THREAD

**Issue by trevjonez** [busybusy/DBC-Android#3]
Create a `fails` method on [BlockChecks](https://github.com/busybusy/DBC-Android/blob/master/lib/src/main/java/com/busybusy/dbc/checks/BlockChecks.java) that works like `passes` but expects false from the provided `DbcBlock`

This will convert code such as this:
`require(typeToAdd).isNotNull().passes(subject -> !subject.isInterface());`

to:
`require(typeToAdd).isNotNull().fails(subject -> subject.isInterface());`
which then reduces to:
`require(typeToAdd).isNotNull().fails(Class::isInterface);`

**Comment by jjamminjim** [comment]
You gonna keep both methods?

**Comment by trevjonez** [comment]
Yea the plan was just to add `fails` to make the usage read better
