### ISSUE TITLE
Add numerical `isNotEqualTo()` checks

### ISSUE THREAD

**Issue by jahunt1** [busybusy/DBC-Android#6]
It would be convenient to be able to say something like:
`require(doubleValue).isNotEqualTo(otherNumber);`

Affects `DoubleCondition`, `IntegralCondition`, and `FloatCondition`

**Comment by trevjonez** [comment]
I am adding the checks to the basic condition which is implemented through the `.equals` method. Will this cover your use case? Also should we add a `isNotNear` for the floating point type objects?

**Comment by jahunt1** [comment]
This should be sufficient. the version with the Comparator gives us what we need for floats and doubles.
